# Generated by Django 2.2 on 2020-11-05 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20201104_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson', to='course.Course', verbose_name='课程'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courselesson',
            name='is_show_list',
            field=models.BooleanField(default=False, verbose_name='是否推荐到课程列表'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='lesson',
            field=models.IntegerField(default=1, verbose_name='第几课时'),
            preserve_default=False,
        ),
    ]
