# Generated by Django 2.2 on 2020-11-05 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20201105_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='brief',
        ),
    ]
