# Generated by Django 2.2 on 2020-11-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='brief',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='详情介绍'),
        ),
    ]
