# Generated by Django 2.2 on 2020-11-05 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_brief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courselesson',
            name='is_show_list',
        ),
        migrations.RemoveField(
            model_name='courselesson',
            name='lesson',
        ),
    ]
